server:
  port: 9091
spring:
  application:
    name: springFood
  datasource:
    url: jdbc:postgresql://localhost:5432/food_db
    username: postgres
    password: gabeman
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
